title: Reginald Muli # your name (or website title) here
logo: "/images/cv pic (2).jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Small boy with an insatiable urge to solve big problems<br>
  Second description 
  <br>This shows that I possess some small but significant coding skills🎉<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile n/a</a> 
 
